services:
  app:
    container_name: ci-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci-db
      MYSQL_USER: ci-user
      MYSQL_PASSWORD: ci-password
    ports:
      - 3306:3306

  db-admin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
